# Site settings
title: Low FOD, No Cod
email: me@lowfodnocod.kiwi
description: "A blog about a Kiwi who is venturing down the path of a low FODMAP diet."
baseurl: ""
url: "http://lowfodnocod.kiwi"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [README.md]
